version: "3.9"
services:
  create-beacon-chain-genesis:
    image: "gcr.io/prysmaticlabs/prysm/cmd/prysmctl"
    command:
      - testnet
      - generate-genesis
      - --fork=${FORK_VERSION}
      - --num-validators=64
      - --genesis-time-delay=15
      - --output-ssz=${BEACON_GENESIS_ROOT}
      - --chain-config-file=${BEACON_CONFIG_ROOT}
      - --geth-genesis-json-in=${GENESIS_ROOT}
      - --geth-genesis-json-out=${GENESIS_ROOT}
    volumes:
      - ./consensus:${CONSENSUS_ROOT}
      - ./execution:${EXECUTION_ROOT}
  
  geth-genesis:
    image: "ethereum/client-go"
    command: --datadir=${EXECUTION_ROOT}/data init ${GENESIS_ROOT}
    volumes:
      - ./consensus:${CONSENSUS_ROOT}
      - ./execution/genesis.json:${GENESIS_ROOT}
      - ./execution:${EXECUTION_ROOT}
    depends_on:
      create-beacon-chain-genesis:
        condition: service_completed_successfully

  beacon-chain:
    image: "gcr.io/prysmaticlabs/prysm/beacon-chain"
    command:
      - --datadir=${CONSENSUS_ROOT}/beacondata
      - --min-sync-peers=0
      - --genesis-state=${BEACON_GENESIS_ROOT}
      - --bootstrap-node=
      - --interop-eth1data-votes
      - --chain-config-file=${BEACON_CONFIG_ROOT}
      - --contract-deployment-block=0
      - --chain-id=${CHAIN_ID}
      - --rpc-host=0.0.0.0
      - --rpc-port=${BEACON_RPC_PORT}
      - --grpc-gateway-host=0.0.0.0
      - --grpc-gateway-port=${BEACON_GRPC_PORT}
      - --execution-endpoint=http://geth:${GETH_AUTH_RPC_PORT}
      - --accept-terms-of-use
      - --jwt-secret=${JWTSECRET_ROOT}
      - --suggested-fee-recipient=${MINER_ADDRESS}
      - --minimum-peers-per-subnet=0
      - --enable-debug-rpc-endpoints
      - --monitoring-port=${BEACON_MONITORING_PORT}
      - --pprofport=${BEACON_PPROF_PORT}
      # - --force-clear-db
    ports:
      - ${BEACON_HOST}:${BEACON_RPC_PORT}:${BEACON_RPC_PORT}
      - ${BEACON_HOST}:${BEACON_GRPC_PORT}:${BEACON_GRPC_PORT}
      - ${BEACON_HOST}:${BEACON_MONITORING_PORT}:${BEACON_MONITORING_PORT}
      - ${BEACON_HOST}:${BEACON_PPROF_PORT}:${BEACON_PPROF_PORT}
      # - 9090:9090
    volumes:
      - ./consensus:${CONSENSUS_ROOT}
      - ./execution:${EXECUTION_ROOT}
    depends_on:
      create-beacon-chain-genesis:
        condition: service_completed_successfully

  geth:
    image: "ethereum/client-go"
    command:
      - --datadir=${EXECUTION_ROOT}/data
      - --syncmode=full
      - --networkid=${CHAIN_ID}
      - --http
      - --http.api=eth,net,txpool
      - --http.addr=0.0.0.0
      - --http.port=${GETH_HTTP_PORT}
      - --http.corsdomain=*
      - --http.vhosts=*
      - --ws
      - --ws.api=eth,net,web3
      - --ws.addr=0.0.0.0
      - --ws.port=${GETH_WS_PORT}
      - --ws.origins=*
      - --authrpc.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=${GETH_AUTH_RPC_PORT}
      - --authrpc.jwtsecret=${JWTSECRET_ROOT}
      # - --allow-insecure-unlock
      # - --unlock=${MINER_ADDRESS}
      # - --password=${PASSWORD_ROOT}
      - --nodiscover
    ports:
      - ${GETH_HOST}:${GETH_AUTH_RPC_PORT}:${GETH_AUTH_RPC_PORT} # AUTH RPC
      - ${GETH_HOST}:${GETH_HTTP_PORT}:${GETH_HTTP_PORT} # RPC
      - ${GETH_HOST}:${GETH_WS_PORT}:${GETH_WS_PORT} # WS
    volumes:
      - ./execution:${EXECUTION_ROOT}
    depends_on:
        geth-genesis:
          condition: service_completed_successfully
        beacon-chain:
          condition: service_started

  validator:
    image: "gcr.io/prysmaticlabs/prysm/validator"
    command:
      - --datadir=${CONSENSUS_ROOT}/validatordata
      - --beacon-rpc-provider=beacon-chain:${BEACON_RPC_PORT}
      - --accept-terms-of-use
      - --interop-num-validators=64
      - --chain-config-file=${BEACON_CONFIG_ROOT}
      # - --force-clear-db
    volumes:
      - ./consensus:${CONSENSUS_ROOT}
    depends_on:
      beacon-chain:
        condition: service_started

#   ###############################################################################
#   ###                               blockscout                                ###
#   ###############################################################################   
#   postgres:
#     image: postgres:13.6
#     restart: always
#     container_name: "postgres"
#     environment:
#       POSTGRES_PASSWORD: ""
#       POSTGRES_USER: "postgres"
#       POSTGRES_HOST_AUTH_METHOD: "trust"
#     volumes:
#       - "postgres-data:/var/lib/postgresql/data"
#     ports:
#       - "5432:5432"

#   blockscout:
#     depends_on:
#       - postgres
#       - geth
#     image: blockscout/blockscout:latest
#     restart: always
#     container_name: "blockscout"
#     links:
#       - postgres:database
#     command:
#       - /bin/sh
#       - -c
#       - |
#         bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()"
#         node init/install.js postgres 5432
#         bin/blockscout start
#     extra_hosts:
#       - "host.docker.internal:host-gateway"
#     env_file:
#       - ./blockscout/common-blockscout.env
#     environment:
#       ETHEREUM_JSONRPC_VARIANT: "geth"
#       ETHEREUM_JSONRPC_HTTP_URL: geth:${GETH_HTTP_PORT}
#       COIN: ETH
#       NETWORK: ${NETWORK_NAME}
#       SUBNETWORK : ${SUBNETWORK}
#       DATABASE_URL: postgresql://postgres:@postgres:5432/blockscout
#       PORT: ${BLOCKSCOUT_PORT}
#     ports:
#       - ${BLOCKSCOUT_HOST}:${BLOCKSCOUT_PORT}:${BLOCKSCOUT_PORT}

# volumes:
#   postgres-data:
